import pandas as pd

def isolate_spring_data():
    print("Loading master results file...")
    # Read the file generated by Phase 3 of your bat file
    df = pd.read_csv("Historical_Alpha_Results.csv") 
    
    initial_len = len(df)
    
    # Convert Date column to datetime objects
    df['Date'] = pd.to_datetime(df['Date'])
    
    # Strictly filter for March 1st, 2026 to present
    spring_df = df[df['Date'] >= '2026-03-21'].copy()
    
    final_len = len(spring_df)
    
    # Save to a brand new file so we don't touch the master
    spring_df.to_csv("Spring_2026_Results.csv", index=False)
    
    print("="*50)
    print(" 🧹 OUT-OF-SAMPLE DATA ISOLATED")
    print("="*50)
    print(f"Total Signals in Master: {initial_len}")
    print(f"Isolated Spring Signals: {final_len} ready for testing.")
    print("-> Saved to: Spring_2026_Results.csv")

if __name__ == "__main__":
    isolate_spring_data()